# Generated by Django 5.0 on 2023-12-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='order',
        ),
    ]
