# Generated by Django 5.0 on 2023-12-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormtest', '0002_remove_todoitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='something',
            field=models.CharField(default='hello', max_length=10),
        ),
    ]
